### ISSUE TITLE
Game crashes after accessing a resource which hasn't been found

### ISSUE THREAD

**Issue by tommz9** [falltergeist/falltergeist#402]
The game is complaining in the console:

```
[ERROR] [RESOURCE MANAGER] Loading file: art/critters/nachldaa.frm [ NOT FOUND]
```

But it crashes after it tries to access the same resource later. It shouldn't try to access a resource which hasn't been loaded.

Backtrace from gdb:

```
(gdb) backtrace 
#0  0x00000000008dc930 in libfalltergeist::Frm::File::actionFrame (this=0x0)
    at /home/tommz/falltergeist/lib/libfalltergeist/src/Frm/File.cpp:143
#1  0x00000000008888f2 in Falltergeist::UI::Animation::Animation (
    this=0x42e03d0, frmName="art/critters/nachldaa.frm", direction=3)
    at /home/tommz/falltergeist/src/UI/Animation.cpp:57
#2  0x00000000007d7fd7 in Falltergeist::Game::CritterObject::setActionAnimation
    (this=0x8dcf590, action="aa")
    at /home/tommz/falltergeist/src/Game/CritterObject.cpp:596
#3  0x00000000007d7336 in Falltergeist::Game::CritterObject::think (
    this=0x8dcf590) at /home/tommz/falltergeist/src/Game/CritterObject.cpp:500
#4  0x00000000007bd048 in Falltergeist::State::Location::think (this=0x1b0da60)
    at /home/tommz/falltergeist/src/State/Location.cpp:416
#5  0x00000000007dca6e in Falltergeist::Game::Game::think (this=0xbdde20)
    at /home/tommz/falltergeist/src/Game/Game.cpp:404
#6  0x00000000007daea6 in Falltergeist::Game::Game::run (this=0xbdde20)
    at /home/tommz/falltergeist/src/Game/Game.cpp:161
#7  0x0000000000755755 in main (argc=1, argv=0x7fffffffe168)
    at /home/tommz/falltergeist/main.cpp:44
```

Running on Ubuntu 15.04 in VirtualBox.
Game version: https://github.com/falltergeist/falltergeist/tree/50502225985c5ade5cd936600c4019c5b6e904a0

**Comment by phobos2077** [comment]
I think in our current implementation, cases when resource may not exist are not handled at all. 
Something to look out for while we refactor Resource Manager #365 .

**Comment by phobos2077** [comment]
By the way, could you clarify how exactly did you triggered this error?

**Comment by tommz9** [comment]
Just run the game with the default configuration. At the loading it complains about the missing resource and then it crashes if I go a little to the west. Probably the file is missing in my version of the game. But anyway it  just crash. Better end with an error mesage or use some placeholder data/graphics instead.

**Comment by alexeevdv** [comment]
Can you please share you game data files with us? Just for testing :)

**Comment by tommz9** [comment]
Well I can, but wouldn't that be illegal? Since it is copyrighted :) just remove the file from your own data archive, that should do the same effect.
