### ISSUE TITLE
The game crashes if movie.lst is an empty file

### ISSUE THREAD

**Issue by mulander** [falltergeist/falltergeist#466]
This was discovered as an ongoing effort to port Falltergeist to OpenBSD. Not a huge bug but still annoying to debug if it happens.

```
[INFO] [RENDERER] [OK]
[INFO] [RENDERER] Generating buffers
[INFO] [AUDIO] - SDL_Init - [OK]
[INFO] [AUDIO] - Mix_OpenAudio - [OK]
[INFO] [GAME] Starting main loop
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 17) >= this->size() (which is 0)
Abort trap (core dumped) 
$ 

```

```
(gdb) bt
#0  0x0000187af99a5a1a in thrkill () at <stdin>:2
#1  0x0000187af99a1109 in *_libc_abort () at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x0000187b5cb2ddd5 in __gnu_cxx::__verbose_terminate_handler ()
    at /usr/obj/ports/gcc-4.9.3/gcc-4.9.3/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x0000187b5cb2b968 in __cxxabiv1::__terminate (handler=<optimized out>)
    at /usr/obj/ports/gcc-4.9.3/gcc-4.9.3/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x0000187b5cb2b9d1 in std::terminate () at /usr/obj/ports/gcc-4.9.3/gcc-4.9.3/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x0000187b5cb2bbe8 in __cxxabiv1::__cxa_throw (obj=0x187b3c7c4380, tinfo=0x187b5cdd4a30 <typeinfo for std::out_of_range>, dest=
    0x187b5cb49c20 <std::out_of_range::~out_of_range()>) at /usr/obj/ports/gcc-4.9.3/gcc-4.9.3/libstdc++-v3/libsupc++/eh_throw.cc:87
#6  0x0000187b5cb8db4c in std::__throw_out_of_range_fmt (__fmt=<optimized out>)
    at /usr/obj/ports/gcc-4.9.3/gcc-4.9.3/libstdc++-v3/src/c++11/functexcept.cc:101
#7  0x00001878b93e9e52 in std::vector<std::string, std::allocator<std::string> >::_M_range_check (this=0x187ad09bfe68, __n=17)
    at /usr/local/include/c++/4.9.3/bits/stl_vector.h:803
#8  0x00001878b93e86ed in std::vector<std::string, std::allocator<std::string> >::at (this=0x187ad09bfe68, __n=17)
    at /usr/local/include/c++/4.9.3/bits/stl_vector.h:824
#9  0x00001878b94273ba in Falltergeist::State::Movie::init (this=0x187b713d4a00)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/State/Movie.cpp:71
#10 0x00001878b93a0cc1 in Falltergeist::Game::Game::pushState (this=0x187aefe8c400, state=0x187b713d4a00)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/Game.cpp:138
#11 0x00001878b945f1bb in Falltergeist::State::Start::think (this=0x187b629f8a00)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/State/Start.cpp:93
#12 0x00001878b93a28eb in Falltergeist::Game::Game::think (this=0x187aefe8c400)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/Game.cpp:428
#13 0x00001878b93a1058 in Falltergeist::Game::Game::run (this=0x187aefe8c400)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/Game.cpp:169
#14 0x00001878b93343e1 in main (argc=1, argv=0x7f7ffffd5668) at /home/mulander/github.com/falltergeist/falltergeist-0.3/main.cpp:41
```

**Comment by alexeevdv** [comment]
Well... obviously it should not be empty :)
