### ISSUE TITLE
Crash when starting a new game (Falltergeist::Format::Frm::File::framesPerDirection)

### ISSUE THREAD

**Issue by mulander** [falltergeist/falltergeist#467]
From the ongoing process of porting Falltergeist to OpenBSD

```
Core was generated by `falltergeist'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000035d357550f4 in Falltergeist::Format::Frm::File::framesPerDirection (this=0x0)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Format/Frm/File.cpp:140
140         return _framesPerDirection;
```

```
(gdb) bt
#0  0x0000035d357550f4 in Falltergeist::Format::Frm::File::framesPerDirection (this=0x0)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Format/Frm/File.cpp:140
#1  0x0000035d357b4f6c in Falltergeist::Graphics::Animation::Animation (this=0x36007874200, filename=...)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Graphics/Animation.cpp:61
#2  0x0000035d35864c37 in Falltergeist::Base::make_unique<Falltergeist::Graphics::Animation, std::string const&> ()
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/UI/../Base/StlFeatures.h:61
#3  0x0000035d35863d11 in Falltergeist::UI::Animation::Animation (this=0x35fe5945000, frmName=..., direction=0)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/UI/Animation.cpp:61
#4  0x0000035d3579a3ac in Falltergeist::Game::CritterObject::setActionAnimation (this=0x35fd3acec00, action=...)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/CritterObject.cpp:612
#5  0x0000035d3579a875 in Falltergeist::Game::CritterObject::_generateUi (this=0x35fd3acec00)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/CritterObject.cpp:636
#6  0x0000035d357ac124 in Falltergeist::Game::Object::setFID (this=0x35fd3acec00, value=16777243)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/Object.cpp:92
#7  0x0000035d357b30d6 in Falltergeist::Game::ObjectFactory::createObject (this=0x35f8f13d180, PID=16777268)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/ObjectFactory.cpp:317
#8  0x0000035d3581259d in Falltergeist::State::Location::setLocation (this=0x35f85c75c00, name=...)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/State/Location.cpp:265
#9  0x0000035d35811232 in Falltergeist::State::Location::init (this=0x35f85c75c00)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/State/Location.cpp:112
#10 0x0000035d357a0cc1 in Falltergeist::Game::Game::pushState (this=0x3603426ea00, state=0x35f85c75c00)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/Game.cpp:138
#11 0x0000035d357a0fac in Falltergeist::Game::Game::setState (this=0x3603426ea00, state=0x35f85c75c00)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/Game.cpp:159
#12 0x0000035d3583af22 in Falltergeist::State::PlayerCreate::doDone (this=0x35f84473800)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/State/PlayerCreate.cpp:649
#13 0x0000035d3583ae22 in Falltergeist::State::PlayerCreate::onDoneButtonClick (this=0x35f84473800, event=0x35fa0305f80)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/State/PlayerCreate.cpp:627
#14 0x0000035d3583a14b in Falltergeist::State::PlayerCreate::onButtonClick (this=0x35f84473800, event=0x35fa0305f80)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/State/PlayerCreate.cpp:517
#15 0x0000035d35840f4e in std::_Mem_fn<void (Falltergeist::State::PlayerCreate::*)(Falltergeist::Event::Mouse*)>::operator()<Falltergeist::Event::Mouse*, void>(Fa
lltergeist::State::PlayerCreate*, Falltergeist::Event::Mouse*&&) const (this=0x35fee70d5a0, __object=0x35f84473800)
    at /usr/local/include/c++/4.9.3/functional:569
---Type <return> to continue, or q <return> to quit--- 
#16 0x0000035d3583ff14 in std::_Bind<std::_Mem_fn<void (Falltergeist::State::PlayerCreate::*)(Falltergeist::Event::Mouse*)> (Falltergeist::State::PlayerCreate*, s
td::_Placeholder<1>)>::__call<void, Falltergeist::Event::Mouse*&&, 0ul, 1ul>(std::tuple<Falltergeist::Event::Mouse*&&>&&, std::_Index_tuple<0ul, 1ul>) (
    this=0x35fee70d5a0, __args=...) at /usr/local/include/c++/4.9.3/functional:1264
#17 0x0000035d3583e284 in std::_Bind<std::_Mem_fn<void (Falltergeist::State::PlayerCreate::*)(Falltergeist::Event::Mouse*)> (Falltergeist::State::PlayerCreate*, s
td::_Placeholder<1>)>::operator()<Falltergeist::Event::Mouse*, void>(Falltergeist::Event::Mouse*&&) (this=0x35fee70d5a0)
    at /usr/local/include/c++/4.9.3/functional:1323
#18 0x0000035d3583cd80 in std::_Function_handler<void (Falltergeist::Event::Mouse*), std::_Bind<std::_Mem_fn<void (Falltergeist::State::PlayerCreate::*)(Fallterge
ist::Event::Mouse*)> (Falltergeist::State::PlayerCreate*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, Falltergeist::Event::Mouse*) (
    __functor=..., __args#0=0x35fa0305f80) at /usr/local/include/c++/4.9.3/functional:2039
#19 0x0000035d35746cb3 in std::function<void (Falltergeist::Event::Mouse*)>::operator()(Falltergeist::Event::Mouse*) const (this=0x3601f464c60, 
    __args#0=0x35fa0305f80) at /usr/local/include/c++/4.9.3/functional:2439
#20 0x0000035d357469b8 in Falltergeist::Event::Dispatcher::Task<Falltergeist::Event::Mouse>::perform (this=0x35fd7ed7f00)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Event/Dispatcher.cpp:60
#21 0x0000035d3573f722 in Falltergeist::Event::Dispatcher::processScheduledEvents (this=0x35fb53590e0)
    at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Event/Dispatcher.cpp:82
#22 0x0000035d357a22c5 in Falltergeist::Game::Game::handle (this=0x3603426ea00) at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/Game.cpp:403
#23 0x0000035d357a104c in Falltergeist::Game::Game::run (this=0x3603426ea00) at /home/mulander/github.com/falltergeist/falltergeist-0.3/src/Game/Game.cpp:168
#24 0x0000035d357343e1 in main (argc=1, argv=0x7f7ffffc2fc8) at /home/mulander/github.com/falltergeist/falltergeist-0.3/main.cpp:41
(gdb)
```

**Comment by isage** [comment]
If you want to port it to *bsd - port it. Pull requests are welcome.
However, bug reports against not supported platforms are not.

**Comment by mulander** [comment]
@isage that's a first pass I do intend to follow up with patches. If the bug reports are annoying I will just refrain from doing that (it was easier to just file this as I continued to investigate the initial build state).

**Comment by isage** [comment]
@mulander they kinda is, sorry. We just can't (or want to) really do anything about it right now.

**Comment by mulander** [comment]
@isage feel free to close all down filed by me. I'll fork the repo and will join the jabber channel for any upstream required reports (will close the reports down myself after I copy them to my fork).
